image:  $DOCKER_REGISTRY/maven:3.6.3-openjdk-17

cache:
  paths:
    - .m2/repository

stages:
  - maven-test
  - maven-deploy
  - release

default:
  tags:
    - docker-runner

variables:
  GIT_STRATEGY: fetch
  GIT_DEPTH: "0"

maven-:
  stage: maven-test
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual
      allow_failure: true
  script:
    - echo $MAVEN_USERNAME
    - echo "<settings>
      <servers>
      <server>
      <id>$MAVEN_REPO_ID</id>
      <username>$MAVEN_USERNAME</username>
      <password>$MAVEN_PASSWORD</password>
      </server>
      </servers>
      <mirrors>
      <mirror>
      <id>$MAVEN_REPO_ID</id>
      <mirrorOf>*</mirrorOf>
      <name>Paz Internal Repo</name>
      <url>$MAVEN_URL</url>
      </mirror>
      </mirrors>
      </settings>"  > ~/.m2/settings.xml
    - cat ~/.m2/settings.xml
    - mvn clean test -PthinJar

maven-deploy:
  stage: maven-deploy
  allow_failure: true
  only:
    - master
  script:
    - echo $MAVEN_USERNAME
    - echo "<settings>
      <servers>
      <server>
      <id>$MAVEN_REPO_ID</id>
      <username>$MAVEN_USERNAME</username>
      <password>$MAVEN_PASSWORD</password>
      </server>
      </servers>
      <mirrors>
      <mirror>
      <id>$MAVEN_REPO_ID</id>
      <mirrorOf>*</mirrorOf>
      <name>Paz Internal Repo</name>
      <url>$MAVEN_URL</url>
      </mirror>
      </mirrors>
      </settings>"  > ~/.m2/settings.xml
    - cat ~/.m2/settings.xml
    - mvn clean deploy -PthinJar

semantic-release:
  stage: release
  image: node:20
  needs: ["maven-deploy"]
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: '$CI_COMMIT_BRANCH =~ /^release\/.+$/'
  before_script:
    - node -v && npm -v
    - test -f package.json || npm init -y
    - npm i -D semantic-release @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/changelog @semantic-release/git @semantic-release/gitlab
  script:
    - npx semantic-release
  tags:
    - docker-runner

semantic-release-rc:
  stage: release
  image: node:20
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^release\/.+$/'
  before_script:
    - node -v && npm -v
    - test -f package.json || npm init -y
    - npm i -D semantic-release @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/changelog @semantic-release/git @semantic-release/gitlab
    - git config user.name "semantic-release-bot"
    - git config user.email "semantic-release-bot@example.com"
  script:
    - npx semantic-release
  tags:
    - docker-runner