am:
  service:
    enginName: AM
    enginVersion: 403.1.1493.0
    handlingMode: 1
    inputAsArray: true
    multiTech: false
    password: 123
    url: https://web-star-nta.abriment.mohaymen.ir
    user: admin
bdmp:
  service:
    engineName: LADW
    engineVersion: 403.1.1508.0
    handlingMode: 1
    inputAsArray: true
    multiTech: false
    showSimorghRowsFromPage: 0
    showSimorghRowsToPage: 20
    url: https://web-star-nta.abriment.mohaymen.ir